# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u5b57')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u4e13\u7528',
                'verbose_name_plural': '\u6d4b\u8bd5\u4e13\u7528',
            },
        ),
    ]
